apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "food-web.fullname" . | default .Chart.Name }}
  labels:
    app: {{ include "food-web.name" . | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "food-web.name" . | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ include "food-web.name" . | default .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {{ toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 6 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 6 }}
      affinity: {{ toYaml .Values.affinity | nindent 6 }}
